environment: production
kusama:
  db:
    uri: "mongodb://test:test@kusama-mongodb-headless.kusama.svc.cluster.local/otv?tls=false&replicaSet=rs0"
  be:
    secret: test
    domain: kusama.w3f.community
    apiEndpoints: 
      - "wss://kusama-rpc.polkadot.io"
      - "wss://kusama.api.onfinality.io/public-ws"
      - "wss://kusama-rpc.dwellir.com"
      - "wss://kusama.public.curie.radiumblock.xyz/ws"
    matrix:   
      room: "a"
      userId: "a"
  mongo_express:
    #Currently shared-vpn-ip entries in vault
    whitelist_source_ips: "*"
    domain: w3f.community
